# Generated by Django 3.0.4 on 2020-04-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplemodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='name',
            table=None,
        ),
    ]
