# Generated by Django 3.0.4 on 2020-04-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplemodel', '0003_name_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='option',
            field=models.BooleanField(),
        ),
    ]
