# Generated by Django 3.0.4 on 2020-04-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplemodel', '0004_auto_20200417_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='option',
            field=models.BooleanField(default=False),
        ),
    ]
