# Generated by Django 3.0.4 on 2020-04-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplemodel', '0005_auto_20200417_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
