# Generated by Django 3.0.4 on 2020-04-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplemodel', '0007_auto_20200417_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
