# Generated by Django 3.0.4 on 2020-04-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplemodel', '0009_auto_20200417_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
