# Generated by Django 3.0.4 on 2020-04-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplemodel', '0012_crops_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='crops',
            name='essentialcrop',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
