# Generated by Django 3.0.4 on 2020-05-02 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samplemodel', '0013_crops_essentialcrop'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='crops',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samplemodel.Farmer'),
        ),
        migrations.CreateModel(
            name='actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actorname', models.CharField(max_length=100)),
                ('movies', models.ManyToManyField(to='samplemodel.movies')),
            ],
        ),
    ]
