# Generated by Django 3.0.4 on 2020-05-14 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samplemodel', '0019_auto_20200514_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samplemodel.Farmer'),
        ),
    ]
